"""empty message

Revision ID: 239926e81e16
Revises: be497f97d8f3
Create Date: 2020-08-27 19:39:07.675903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239926e81e16'
down_revision = 'be497f97d8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_image_historys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False, comment='ファイルパス'),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('update_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_image_historys')
    # ### end Alembic commands ###
