"""empty message

Revision ID: 25a53adf5765
Revises: 
Create Date: 2020-06-28 20:11:50.654930

"""
from alembic import op
import sqlalchemy as sa
from app.const import constant


# revision identifiers, used by Alembic.
revision = '25a53adf5765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission', sa.Integer(), server_default=str(constant.PERMISSION_NOMAL), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission')
    # ### end Alembic commands ###
