"""empty message

Revision ID: e85c926ce3e2
Revises: 25a53adf5765
Create Date: 2020-08-11 19:31:24.847873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e85c926ce3e2'
down_revision = '25a53adf5765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_user_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_user_id')
    # ### end Alembic commands ###
